version: '3'

services:
  redis-container:
    image: redis:latest
    hostname: redis-container
    ports:
      - 6379:6379
    networks:
      - network1

  simapi-container:
    image: 316590403336.dkr.ecr.us-east-1.amazonaws.com/fpgasim:fpgasim
    ports:
      - 5000:5000
      - 12346:12346
    depends_on:
      - redis-container
    networks:
      - network1

networks:
  network1:
    external:
      name: network1
